name: physical
version: 0.0.1
description: A lightweight Dart library for dealing with physical quantities, units, and conversions.
homepage: https://github.com/nebkat/dart-physical
repository: https://github.com/nebkat/dart-physical
documentation: https://github.com/nebkat/dart-physical/blob/master/README.md
environment:
  sdk: '>=3.3.0 <4.0.0'
dev_dependencies:
  test: ^1.26.0
  lints: ^4.0.0
